name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - PrinsFrank
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      options:
        - label: I have searched the existing issues and found no similar reports
          required: true
  - type: checkboxes
    attributes:
      label: Are you using the latest version of this package?
      options:
        - label: The issue I'm reporting exists in the latest release
          required: true
  - type: checkboxes
    attributes:
      label: Can other PDF readers read the file?
      options:
        - label: The PDF I'm trying to read opens correctly in at least one other PDF reader
          required: true
