name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
  - PrinsFrank
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues and found no similar reports
          required: true
  - type: checkboxes
    attributes:
      label: Are you using the latest version of this package?
      description: Please make sure you have updated to the most recent version and that the bug still exists there (`composer require prinsfrank/pdfparser`)
      options:
        - label: The issue I'm reporting exists in the latest release
          required: true
  - type: checkboxes
    attributes:
      label: Can other PDF readers read the file?
      description: Please make sure you're reading a valid PDF file
      options:
        - label: The PDF I'm trying to read opens correctly in at least one other PDF reader
          required: true
